=== balazsfalvi/balazsfalvi_gergo_xml_gyak/XMLFeladatWCD0QI/DomParseWCD0QI/src/hu/domparse/wcd0qi/XMLSchemaWCD0QI.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="webshop" xmlns="webshop">
    <xs:element name="webshop">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="geprendeles" type="geprendelesType"/>
                    <xs:element name="szamitogep" type="szamitogepType"/>
                    <xs:element name="specifikacio" type="specifikacioType"/>
                    <xs:element name="rendeles" type="rendelesType"/>
                    <xs:element name="elado" type="eladoType"/>
                    <xs:element name="vasarlo" type="vasarloType"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="geprendelesID_PK">
            <xs:selector xpath="geprendeles"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="szamitogepID_PK">
            <xs:selector xpath="szamitogep"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="specifikacioID_PK">
            <xs:selector xpath="specifikacio"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="rendelesID_PK">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="eladoID_PK">
            <xs:selector xpath="elado"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="vasarloID_PK">
            <xs:selector xpath="vasarlo"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="szamitogepID_FK" refer="szamitogepID_PK">
            <xs:selector xpath="geprendeles"/>
            <xs:field xpath="@szamitogepId"/>
        </xs:keyref>
        <xs:keyref name="rendelesID_FK" refer="rendelesID_PK">
            <xs:selector xpath="geprendeles"/>
            <xs:field xpath="@rendelesId"/>
        </xs:keyref>
        <xs:keyref name="specID_FK" refer="specifikacioID_PK">
            <xs:selector xpath="szamitogep"/>
            <xs:field xpath="@specId"/>
        </xs:keyref>
        <xs:keyref name="eladoId_FK" refer="eladoID_PK">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@eladoId"/>
        </xs:keyref>
        <xs:keyref name="vasarloId_FK" refer="vasarloID_PK">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@vasarloId"/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name="telepulesType">
        <xs:sequence>
            <xs:element name="irsz" type="xs:unsignedShort" />
            <xs:element name="varos" type="xs:string" />
            <xs:element name="utca" type="xs:string" />
            <xs:element name="hazszam" type="xs:unsignedByte" />
            <xs:element name="emelet" type="xs:unsignedByte" />
            <xs:element name="ajto" type="xs:unsignedByte" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="geprendelesType">
        <xs:sequence>
            <xs:element name="darab" type="xs:unsignedByte" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
        <xs:attribute name="szamitogepId" type="xs:unsignedByte" use="required" />
        <xs:attribute name="rendelesId" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="szamitogepType">
        <xs:sequence>
            <xs:element name="ar" type="xs:unsignedInt" />
            <xs:element name="elnevezes" type="xs:string" />
            <xs:element name="kategoria" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
        <xs:attribute name="specId" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="specifikacioType">
        <xs:sequence>
            <xs:element name="alaplap" type="xs:string" />
            <xs:element name="videokartya" type="xs:string" />
            <xs:element name="memoria" type="xs:string" />
            <xs:element name="tapegyseg" type="xs:string" />
            <xs:element name="processzor" type="xs:string" />
            <xs:element name="tarhely" type="xs:string" />
            <xs:element name="egyeb" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="rendelesType">
        <xs:sequence>
            <xs:element name="datum" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
        <xs:attribute name="eladoId" type="xs:unsignedByte" use="required" />
        <xs:attribute name="vasarloId" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="eladoType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="email" type="xs:string" />
            <xs:element name="telszam" type="xs:long" />
            <xs:element name="telepules" type="xs:string" />
            <xs:element name="ertekeles" type="xs:unsignedByte" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="vasarloType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="telefonszam" type="xs:long" />
            <xs:element name="email" type="xs:string" />
            <xs:element name="lackim" type="telepulesType">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
    </xs:complexType>
</xs:schema>

=== balazsfalvi/balazsfalvi_gergo_xml_gyak/XMLFeladatWCD0QI/DomParseWCD0QI/src/hu/domparse/wcd0qi/XMLWCD0QI.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><webshop xmlns="webshop" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="webshop XMLSchemaWCD0QI.xsd">
    <geprendeles id="1" rendelesId="1" szamitogepId="1">
        <darab>2</darab>
    </geprendeles>

    <szamitogep id="1" specId="1">
        <ar>66000</ar>
        <elnevezes>Irodai</elnevezes>
        <kategoria>Alacsony</kategoria>
    </szamitogep>
    <specifikacio id="1">
        <alaplap>ASUS T4104F</alaplap>
        <videokartya>AMD 8GB</videokartya>
        <memoria>4GB Viper X</memoria>
        <tapegyseg>400W</tapegyseg>
        <processzor>Intel Core i3 3900F</processzor>
        <tarhely>200GB Kingstone HDD</tarhely>
        <egyeb>CD író/olvasó</egyeb>
    </specifikacio>
    <rendeles eladoId="1" id="1" vasarloId="1">
        <datum>2014.01.12</datum>
    </rendeles>
    <elado id="1">
        <nev>Kocsis Sándor</nev>
        <email>kocsis@sandor.hu</email>
        <telszam>+36702552432</telszam>
        <telepules>Szeged</telepules>
        <ertekeles>5</ertekeles>
    </elado>
    <vasarlo id="1">
        <nev>Varga Bela</nev>
        <telefonszam>+3652412414</telefonszam>
        <email>bela@varga.hu</email>
        <lackim>
            <irsz>4200</irsz>
            <varos>Szeged</varos>
            <utca>Arany Janos</utca>
            <hazszam>10</hazszam>
            <emelet>1</emelet>
            <ajto>3</ajto>
        </lackim>
    </vasarlo>
    <geprendeles id="2" rendelesId="2" szamitogepId="2">
        <darab>6</darab>
    </geprendeles>
    <szamitogep id="2" specId="2">
        <ar>1000000</ar>
        <elnevezes>csúcs</elnevezes>
        <kategoria>csúcs</kategoria>
    </szamitogep>
    <specifikacio id="2">
        <alaplap>ASUS T1905F</alaplap>
        <videokartya>AMD 16GB</videokartya>
        <memoria>32 Viper XX</memoria>
        <tapegyseg>500W</tapegyseg>
        <processzor>Intel Core i9 9600F</processzor>
        <tarhely>3TB Kingstone SSD</tarhely>
        <egyeb>CD író/olvasó, processzor vízhűtő</egyeb>
    </specifikacio>
    <rendeles eladoId="1" id="2" vasarloId="1">
        <datum>2015.01.12</datum>
    </rendeles>
    <elado id="2">
        <nev>Kocsis Sándorkakas</nev>
        <email>kocsis@sandor.hu</email>
        <telszam>+36702552432</telszam>
        <telepules>Miskolc</telepules>
        <ertekeles>4</ertekeles>
    </elado>
    <vasarlo id="2">
        <nev>Varga Andras</nev>
        <telefonszam>+3652412414</telefonszam>
        <email>andras@varga.hu</email>
        <lackim>
            <irsz>3900</irsz>
            <varos>Szerencs</varos>
            <utca>Kovacs Janos</utca>
            <hazszam>50</hazszam>
            <emelet>11</emelet>
            <ajto>23</ajto>
        </lackim>
    </vasarlo>
    <vasarlo id="3">
        <nev>Kiss Piroska</nev>
        <telefonszam>+35350540235</telefonszam>
        <email>kiss@piroska.hu</email>
        <lackim>
            <irsz>4500</irsz>
            <varos>Szombathely</varos>
            <utca>Petőfi Sándor</utca>
            <hazszam>45</hazszam>
            <emelet>2</emelet>
            <ajto>3</ajto>
        </lackim>
    </vasarlo>
    <rendeles eladoId="1" id="3" vasarloId="3">
        <datum>2014.01.12</datum>
    </rendeles>
    <geprendeles id="3" rendelesId="3" szamitogepId="1">
        <darab>34</darab>
    </geprendeles>
</webshop>

=== balazsfalvi/balazsfalvi_gergo_xml_gyak/XMLFeladatWCD0QI/DomParseWCD0QI/out/production/DomParseWCD0QI/hu/domparse/wcd0qi/XMLWCD0QI_out.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><webshop xmlns="webshop" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="webshop XMLSchemaWCD0QI.xsd">
    <geprendeles id="1" rendelesId="1" szamitogepId="1">
        <darab>2</darab>
    </geprendeles>
    <szamitogep id="1" specId="1">
        <ar>75000</ar>
        <elnevezes>Irodai</elnevezes>
        <kategoria>alacsony</kategoria>
    </szamitogep>
    <specifikacio id="1">
        <alaplap>ASUS T4104F</alaplap>
        <videokartya>AMD 8GB</videokartya>
        <memoria>4GB Viper X</memoria>
        <tapegyseg>400W</tapegyseg>
        <processzor>Intel Core i3 3900F</processzor>
        <tarhely>200GB Kingstone HDD</tarhely>
        <egyeb>CD író/olvasó</egyeb>
    </specifikacio>
    <rendeles eladoId="1" id="1" vasarloId="1">
        <datum>2014.01.12</datum>
    </rendeles>
    <elado id="1">
        <nev>Kocsis Sándor</nev>
        <email>kocsis@sandor.hu</email>
        <telszam>+36702552432</telszam>
        <telepules>Szeged</telepules>
        <ertekeles>5</ertekeles>
    </elado>
    <vasarlo id="1">
        <nev>Varga Bela</nev>
        <telefonszam>404124024</telefonszam>
        <email>vb@a.q</email>
        <lackim>
            <irsz>3880</irsz>
            <varos>Ózd</varos>
            <utca>1</utca>
            <hazszam>2</hazszam>
            <emelet>1</emelet>
            <ajto>3</ajto>
        </lackim>
    </vasarlo>
    <geprendeles id="2" rendelesId="2" szamitogepId="2">
        <darab>2</darab>
    </geprendeles>
    <szamitogep id="2" specId="2">
        <ar>500000</ar>
        <elnevezes>Gamer</elnevezes>
        <kategoria>csúcs</kategoria>
    </szamitogep>
    <specifikacio id="2">
        <alaplap>ASUS T9104F</alaplap>
        <videokartya>AMD 16GB</videokartya>
        <memoria>32GB Viper X</memoria>
        <tapegyseg>600W</tapegyseg>
        <processzor>Intel Core i9 9400F</processzor>
        <tarhely>2TB Kingstone SSD</tarhely>
        <egyeb>CD író/olvasó, processzor vízhűtő</egyeb>
    </specifikacio>
    <rendeles eladoId="1" id="2" vasarloId="1">
        <datum>2015.01.12</datum>
    </rendeles>
    <elado id="2">
        <nev>Kocsis Sándorkakas</nev>
        <email>kocsis@sandor.hu</email>
        <telszam>+36702552432</telszam>
        <telepules>Miskolc</telepules>
        <ertekeles>4</ertekeles>
    </elado>
    <vasarlo id="2">
        <nev>Varga Andras</nev>
        <telefonszam>+3652412414</telefonszam>
        <email>andras@varga.hu</email>
        <lackim>
            <irsz>3900</irsz>
            <varos>Szerencs</varos>
            <utca>Kovacs Janos</utca>
            <hazszam>50</hazszam>
            <emelet>11</emelet>
            <ajto>23</ajto>
        </lackim>
    </vasarlo>
</webshop>
